### ISSUE TITLE
Python interpreter should check for python2/python3 runner syntax

### ISSUE THREAD

**Issue by Yoav11** [CaribouJohn/pysys-vscode-extension#7]
When the extesion starts it should check for the variations on python that might allow it to work:

- default = python -m pysys
- python3 -m pysys
- py -3 -m pysys
- others?

If none work we need to produce output/popup saying why and that the user should install python and or pysys - possibly giving links/ commands (python -m pip install pysys)

Note pysys 1.6 has a dependency on python 3.7+

So additionally we might want to consider on a version of python less than that suggesting upgrade to 3.7/pysys 1.6

**Comment by CaribouJohn** [comment]
Additionally perhaps we can put a text node into the view to indicate it is inactive because pysys not found

**Comment by CaribouJohn** [comment]
merged pull request
